apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pet-clinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-pet-clinic
  template:
    metadata:
      labels:
        app: k8s-pet-clinic
    spec:
      containers:
      - name: k8s-pet-clinic
        image: testimage:tag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-pet-clinic
spec:
  selector:
    app: k8s-pet-clinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
